import os

from dotenv import load_dotenv
from langchain_groq import ChatGroq

from app.database.connection import get_connection

load_dotenv()


llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)


SQL_WRITER_PROMPT = """
You are a SQL generation agent.

Your job is to convert a user's natural language question
and the planner's instructions into ONE valid PostgreSQL SELECT query.

IMPORTANT RULES:

1. Generate ONLY SELECT queries.
2. Never generate INSERT, UPDATE, DELETE, DROP, ALTER,
   TRUNCATE, CREATE, or other write operations.
3. Use ONLY tables and columns that exist in the provided schema.
4. Do not invent tables or columns.
5. Use PostgreSQL syntax.
6. Return ONLY the SQL query.
7. Do not use markdown code fences.
8. For revenue calculations, use order_items.quantity *
   order_items.unit_price when appropriate.

DATABASE SCHEMA:

{schema}

USER QUESTION:

{question}

PLANNER'S PLAN:

{plan}

PREVIOUS SQL:

{previous_sql}

VALIDATION FEEDBACK:

{validation_message}
"""

def get_schema():

    connection = get_connection()

    try:
        cursor = connection.cursor()

        cursor.execute("""
            SELECT
                table_name,
                column_name,
                data_type
            FROM information_schema.columns
            WHERE table_schema = 'public'
            ORDER BY table_name, ordinal_position;
        """)

        rows = cursor.fetchall()

        schema = {}

        for table_name, column_name, data_type in rows:

            if table_name not in schema:
                schema[table_name] = []

            schema[table_name].append(
                f"{column_name} ({data_type})"
            )

        return schema

    finally:
        connection.close()


def generate_sql(
    question: str,
    plan: str,
    previous_sql: str = "",
    validation_message: str = ""
) -> str:

    schema = get_schema()

    prompt = SQL_WRITER_PROMPT.format(
        schema=schema,
        question=question,
        plan=plan,
        previous_sql=previous_sql,
        validation_message=validation_message
    )

    response = llm.invoke(prompt)

    sql = response.content.strip()

    print("\n[DEBUG] SQL generated by LLM:")
    print(sql)

    # Remove markdown fences if the model adds them
    sql = sql.replace("```sql", "")
    sql = sql.replace("```", "")

    return sql.strip()